# _config.yml

# Basic settings
title: FlagoDNA Developer
description: Mlampah ing tresno
theme: jekyll-theme-cayman
show_downloads: false

# Site metadata
url: "https://flagodna-developer.github.io"
author: "FlagoDNA Developer Labs"
